# Makefile

# Adapted from Lecture Book Part 24: Tiffany Timbers, Nov 2018
# 24  Data analysis pipelines with GNU Make
# https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/180-pipelines-make.html#gnu-make-as-a-data-analysis-pipeline-tool

# Before running the commands below ensure your environment has
# the required dependencies by running $ docker compose up.

# Example usage:
# $ make all
# $ make clean

# Setup PHONY targets
.PHONY: all dats figs clean-dats clean-figs clean-all

# run entire analysis
all: report/global_daily_land_temperature_prediction.html

# Data to be generated by analysis
dats: data/global_temp_anomaly_cleaned_full.csv \
data/global_temp_anomaly_cleaned_test.csv.csv \
data/global_temp_anomaly_cleaned_train.csv \
data/global_temp_anomaly_raw.csv \
results/forecast_2030.csv
results/model_results.csv

results/isles.dat : scripts/wordcount.py data/isles.txt
	python scripts/wordcount.py \
	    --input_file=data/isles.txt \
	    --output_file=results/isles.dat
results/abyss.dat : scripts/wordcount.py data/abyss.txt
	python scripts/wordcount.py \
	    --input_file=data/abyss.txt \
	    --output_file=results/abyss.dat
results/last.dat : scripts/wordcount.py data/last.txt
	python scripts/wordcount.py \
	    --input_file=data/last.txt \
	    --output_file=results/last.dat
results/sierra.dat : scripts/wordcount.py data/sierra.txt
	python scripts/wordcount.py \
	    --input_file=data/sierra.txt \
	    --output_file=results/sierra.dat

# plot
figs : images/correlation_heatmap.png \
	images/s.png \

results/figure/isles.png : scripts/plotcount.py results/isles.dat
	python scripts/plotcount.py \
	    --input_file=results/isles.dat \
	    --output_file=results/figure/isles.png
results/figure/abyss.png : scripts/plotcount.py results/abyss.dat
	python scripts/plotcount.py \
	    --input_file=results/abyss.dat \
	    --output_file=results/figure/abyss.png
results/figure/last.png : scripts/plotcount.py results/last.dat
	python scripts/plotcount.py \
	    --input_file=results/last.dat \
	    --output_file=results/figure/last.png
results/figure/sierra.png : scripts/plotcount.py results/sierra.dat
	python scripts/plotcount.py \
	    --input_file=results/sierra.dat \
	    --output_file=results/figure/sierra.png

# write the report
reports/global_daily_land_temperature_prediction.html : reports/global_daily_land_temperature_prediction.qmd figs
	quarto render report/global_daily_land_temperature_prediction.qmd

clean-dats :
	rm -f results/isles.dat \
	    results/abyss.dat \
	    results/last.dat \
	    results/sierra.dat

clean-figs :
	rm -f results/figure/isles.png \
	results/figure/abyss.png \
	results/figure/last.png \
	results/figure/sierra.png

clean : clean-dats \
	clean-figs
	rm -f reports/global_daily_land_temperature_prediction.html
	rm -rf reports/global_daily_land_temperature_prediction_files