"""
Test suite for the `data_cleaning` function in the data preprocessing script located at `scripts/data_preprocessing.py`.

This script validates the correctness, robustness, and type safety of the
`data_cleaning` preprocessing function used for cleaning the global land average temperature data.

The tests verify:

- Correct output columns and dtypes
- Handling of empty inputs
- Month (1-12), Day (1-31), and Day of Year (1-365) within expected range
- Preservation of unmodified input columns
- Month name column has correct categorical dtype
- Temperature calculation uses anomaly + baseline
- Error handling for invalid input types
- Edge-case behavior for extreme anomaly and year values

Usage
-----
Run all tests and write logs to a directory:

    python tests/test_data_preprocessing.py --logs_path="./logs"

If all tests pass, the `data_preprocessing_tests.log` file will be empty.
"""

import pytest
import pandas as pd
import math
import sys
import os
import logging
import click
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from scripts.data_preprocessing import data_cleaning

# call with : 
# python tests/test_data_preprocessing.py --logs_path="logs"

# run all tests
@click.command()
# path to folder to save logs generated by testing, e.g. "../logs". logs will be saved as .log
@click.option('--logs_path', type=str)
def main(logs_path):
    """
    Run the full test suite for the data preprocessing module.

    Parameters
    ----------
    logs_path : str
        Path to the directory where log files should be written. The directory
        will be created if it does not exist.

    Notes
    -----
    This function configures logging, executes all test functions in sequence,
    and prints a confirmation message when all tests pass. Logs are written into
    a file named `data_preprocessing_tests.log` within the provided logs path.
    """
    # Create logs directory to hold validation logs
    if not os.path.exists(logs_path):
        os.makedirs(logs_path)
    
    # Configure logging
    logging.basicConfig(
        filename=f"{logs_path}/data_preprocessing_tests.log",
        filemode="w",
        format="%(asctime)s - %(message)s",
        level=logging.INFO,
    )
    
    test_returns_dataframe()
    test_empty_returns_empty()
    test_columns()
    test_returned_types()
    test_ranges()
    test_columns_not_modified()
    test_month_names()
    test_add_temperature_column()
    test_set_baseline()
    test_incorrect_types_errors()
    test_anomaly_values()
    test_year_values()
    print("All tests passed.")

# General Test Dataframe
raw_test_data = pd.DataFrame({
    "Date Number" : [1880.001, 1880.004, 1880.007],
    "Year" : [1880, 1880, 1880],
    "Month" : [1, 1, 1],
    "Day" : [1, 2, 3],
    "Day of Year" : [1, 2, 3],
    "Anomaly" : [-0.692, -0.592, -0.673]
})

def test_returns_dataframe():
    """
    Test that a non-empty input DataFrame returns a non-empty DataFrame of type `pandas.DataFrame`.
    """
    cleaned_data = data_cleaning(raw_test_data)
    assert isinstance(cleaned_data, pd.DataFrame)
    assert cleaned_data.loc(0) is not None

def test_empty_returns_empty():
    """
    Test that passing an empty DataFrame returns an empty DataFrame.
    """
    # Empty dataframe
    raw_test_data_empty = pd.DataFrame({
        "Date Number" : pd.Series([], dtype="float64"),
        "Year" : pd.Series([], dtype="int64"),
        "Month" : pd.Series([], dtype="int64"),
        "Day" : pd.Series([], dtype="int64"),
        "Day of Year" : pd.Series([], dtype="int64"),
        "Anomaly" : pd.Series([], dtype="float64")
    })
    assert (data_cleaning(raw_test_data_empty)).empty

def test_columns():
    """
    Test that the cleaned DataFrame contains the correct set of columns. Verify all expected columns are present, no additional columns exist, and the columns are in the expected order.
    """
    expected_column_names = [
        "Year",
        "Month",
        "Day",
        "Day of Year",
        "Anomaly",
        "Temperature",
        "Month_Name"
    ]
    assert data_cleaning(raw_test_data).columns.to_list() == expected_column_names

def test_returned_types():
    """
    Test that all returned columns have the expected dtypes. Calendar fields should have integer values, anomaly and temperature fields should have floating-point values, and Month_Name should be categorical with the proper ordering.
    """
    cleaned_data = data_cleaning(raw_test_data)

    expected_types = {
        "Year": "int64",
        "Month": "int64",
        "Day": "int64",
        "Day of Year": "int64",
        "Anomaly": "float64",
        "Temperature": "float64",
        "Month_Name": pd.CategoricalDtype(categories=['January', 'February', 'March', 'April', 'May', 'June',
                  'July', 'August', 'September', 'October', 'November',
                  'December'], ordered=True)
    }

    assert cleaned_data.dtypes.to_dict() == expected_types

def test_ranges():
    """
    Test that Month, Day, and Day of Year fall within valid ranges after cleaning. Valid ranges are: Month: 1–12, Day: 1–31, Day of Year: 1–365. Ensures that no invalid values are introduced in `data_cleaning()`, not that the input data is within valid ranges (this check is performed during data validation).
    """
    # Month, Day, and Day of Year contain values at edges of expected range
    raw_test_data_range_limits = pd.DataFrame({
        "Date Number" : [0, 0, 0],
        "Year" : [0, 0, 0],
        "Month" : [1, 5, 12],
        "Day" : [1, 15, 31],
        "Day of Year" : [1, 60, 365],
        "Anomaly" : [-0.692, -0.592, -0.673]
    })
    
    cleaned_data_range_limits = data_cleaning(raw_test_data_range_limits)
    assert cleaned_data_range_limits["Month"].between(1, 12).all()
    assert cleaned_data_range_limits["Day"].between(1, 31).all()
    assert cleaned_data_range_limits["Day of Year"].between(1, 365).all()

def test_columns_not_modified():
    """
    Test that key input columns (Year, Month, Day, and Day of Year) remain unmodified after cleaning, i.e. match exactly between input and cleaned output.
    """
    cleaned_data = data_cleaning(raw_test_data)
    assert (cleaned_data["Year"]).equals(raw_test_data["Year"])
    assert (cleaned_data["Month"]).equals(raw_test_data["Month"])
    assert (cleaned_data["Day"]).equals(raw_test_data["Day"])
    assert (cleaned_data["Day of Year"]).equals(raw_test_data["Day of Year"])

def test_month_names():
    """
    Test correctness of the Month_Name categorical column. Ensures all month numbers (from the ordered test set raw_test_data_all_months) map to correct month names.
    """
    # All possible Month values in order
    raw_test_data_all_months = pd.DataFrame({
        "Date Number" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "Year" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "Month" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "Day" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "Day of Year" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "Anomaly" : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    })
    clean_test_data_all_months = data_cleaning(raw_test_data_all_months)
    cleaned_month_list = [
        'January', 
        'February', 
        'March', 
        'April', 
        'May', 
        'June', 
        'July', 
        'August', 
        'September', 
        'October', 
        'November', 
        'December'
    ]
    
    assert(list(clean_test_data_all_months['Month_Name']) == cleaned_month_list)

def test_add_temperature_column():
    """
    Test that the Temperature column is added and computed correctly with the default baseline. The calculation should be: Temperature = Anomaly + baseline.
    """
    cleaned_data = data_cleaning(raw_test_data)
    assert "Temperature" in cleaned_data.columns
    assert math.isclose(cleaned_data["Temperature"][0], 7.898, abs_tol = 0.001)

def test_set_baseline():
    """
    Test that a custom baseline value is computed correctly in the temperature calculation.
    """
    cleaned_data = data_cleaning(raw_test_data, 1.0)
    assert math.isclose(cleaned_data["Temperature"][0], (-0.692 + 1), abs_tol = 0.001)

def test_incorrect_types_errors():
    """
    Test that invalid input dtypes raise `TypeError`, including strings or float inputs for date columns and invalid string inputs for Anomaly column. Note that Anomaly column is cast to float during preprocessing, so integers, floats, or valid numeric strings should not raise an error.
    """
    # Year provided as string
    raw_test_data_string_year = pd.DataFrame({
        "Date Number" : [1],
        "Year" : ["1880"],
        "Month" : [1],
        "Day" : [1],
        "Day of Year" : [1],
        "Anomaly" : [1]
    })

    # Year provided as float
    raw_test_data_float_year = pd.DataFrame({
        "Date Number" : [1],
        "Year" : [1880.5],
        "Month" : [1],
        "Day" : [1],
        "Day of Year" : [1],
        "Anomaly" : [1]
    })

    # Anomaly provided as invalid string
    raw_test_data_string_anomaly = pd.DataFrame({
        "Date Number" : [1],
        "Year" : [1],
        "Month" : [1],
        "Day" : [1],
        "Day of Year" : [1],
        "Anomaly" : ["1,234"]
    })
  
    with pytest.raises(TypeError):
        data_cleaning(raw_test_data_string_year)
        data_cleaning(raw_test_data_float_year)
        data_cleaning(raw_test_data_string_anomaly)

def test_anomaly_types():
    """
    Test that Anomaly values are correctly cast to float when provided
    as integers or numeric strings.
    """

    # Anomaly provided as integers
    df_int = pd.DataFrame({
        "Date Number": [0, 0, 0],
        "Year": [2000, 2000, 2000],
        "Month": [1, 1, 1],
        "Day": [1, 2, 3],
        "Day of Year": [1, 2, 3],
        "Anomaly": [0, 5, -3]
    })
    cleaned_int = data_cleaning(df_int)
    assert cleaned_int["Anomaly"].dtype == "float64"
    assert cleaned_int["Anomaly"].tolist() == [0.0, 5.0, -3.0]

    # Anomaly provided as numeric strings
    df_str = pd.DataFrame({
        "Date Number": [0, 0, 0],
        "Year": [2000, 2000, 2000],
        "Month": [1, 1, 1],
        "Day": [1, 2, 3],
        "Day of Year": [1, 2, 3],
        "Anomaly": ["0.25", "-1.5", "3"]
    })
    cleaned_str = data_cleaning(df_str)
    assert cleaned_str["Anomaly"].dtype == "float64"
    assert cleaned_str["Anomaly"].tolist() == [0.25, -1.5, 3.0]    

def test_anomaly_values():
    """
    Test temperature computation using extreme anomaly values. Check that large positive, large negative, and close to 0 anomalies all produce correct temperature values.
    """
    # Extreme anomaly values
    raw_test_data_anomaly_values = pd.DataFrame({
        "Date Number" : [1880.001, 1880.004, 1880.007],
        "Year" : [1880, 1880, 1880],
        "Month" : [1, 1, 1],
        "Day" : [1, 2, 3],
        "Day of Year" : [1, 2, 3],
        "Anomaly" : [-1000.6543, 1000.444, 0.00000008]
    })

    cleaned_data = data_cleaning(raw_test_data_anomaly_values, 1.0) 
    assert math.isclose(cleaned_data["Temperature"][0], (-1000.6543 + 1.0), abs_tol = 0.001)
    assert math.isclose(cleaned_data["Temperature"][1], (1000.444 + 1.0), abs_tol = 0.001)
    assert math.isclose(cleaned_data["Temperature"][2], (0.00000008 + 1.0), abs_tol = 0.001)


def test_year_values():
    """
    Test that extreme year values are preserved and not altered, including negative years, year zero, and very large years.
    """
    # Extreme year values
    raw_test_data_year_values = pd.DataFrame({
        "Date Number" : [1880.001, 1880.004, 1880.007],
        "Year" : [-2003, 0, 6789543],
        "Month" : [1, 1, 1],
        "Day" : [1, 2, 3],
        "Day of Year" : [1, 2, 3],
        "Anomaly" : [-0.692, -0.592, -0.673]
    })
    cleaned_data = data_cleaning(raw_test_data_year_values, 1.0)
    assert cleaned_data["Year"].equals(raw_test_data_year_values["Year"])

if __name__ == "__main__":
    main()
