# note: run this file using:
# python data_preprocessing.py --read_path="../data/global_temp_anomaly_raw.csv" --write_path="../data/global_temp_anomaly_cleaned" --plots_path="../images" --logs_path="../logs"

# -----------------------------
# Data Handling & Numerical Computation
# -----------------------------
import pandas as pd      # DataFrames for data manipulation
import numpy as np       # Numerical computations and array operations
import os                # OS-level operations (paths, environment variables)

# -----------------------------
# Data Validation
# -----------------------------
import pandera.pandas as pa     # Pandera DataFrame validation
from pandera import Column, Check  # Column-level validation
from deepchecks.tabular.checks import FeatureLabelCorrelation, FeatureFeatureCorrelation # Correlation Validation
from deepchecks.tabular import Dataset # Correlation Validation

# -----------------------------
# Logging & Warnings
# -----------------------------
import warnings    # Issue runtime warnings without stopping execution
import logging     # Logging errors or informational messages
import json        # Convert validation errors or logs to JSON format

# -----------------------------
# Visualization Libraries
# -----------------------------
import altair as alt             # Interactive, declarative plots for EDA

# -----------------------------
# Command Line Arguments
# -----------------------------
import click

# Configure Plot Sizes Globally
plot_size = {'width': 450, 'height': 300}

@click.command()
# path to file to a single raw data file to be read in, e.g. "../data/raw.csv"
@click.option('--read_path', type=str)
# path to folder to save cleaned dataframes (train and test) to, e.g. "../data/cleaned". dataframes will be saved as .csv
@click.option('--write_path', type=str)
# path to folder to save generated plots to, e.g. "../images". plots will be saved as .png
@click.option('--plots_path', type=str)
# path to folder to save logs generated by validation checks to, e.g. "../logs". logs will be saved as .log
@click.option('--logs_path', type=str)
def main(read_path, write_path, plots_path, logs_path):
    # Simplify Working with Large Datasets 
    alt.data_transformers.enable('vegafusion')
    
    # Ignore all warnings from the altair package for pdf rendering, warnings validated first
    # resource for implementation:
    # https://stackoverflow.com/questions/3920502/how-to-suppress-a-third-party-warning-using-warnings-filterwarnings
    warnings.filterwarnings('ignore', module='altair')
    # suppress verbose pandera warning for ipynb and pdf rendering
    warnings.filterwarnings('ignore', module='pandera')

    # Create logs directory to hold validation logs
    if not os.path.exists(logs_path):
        os.makedirs(logs_path)
    
    # Configure logging
    logging.basicConfig(
        filename=f"{logs_path}/validation_errors.log",
        filemode="w",
        format="%(asctime)s - %(message)s",
        level=logging.INFO,
    )
    
    # Load Data from data folder
    df = pd.read_csv(read_path)

    # Clean Data
    df = data_cleaning(df)

    # Perform validation checks that should be on all data
    df = all_data_validation(df)

    # Split data into test and train sets
    train_df, test_df = split_data(df)

    # Visualize distribution of training data
    visualize_distribution(train_df, plots_path) 

    # Perform validation checks that should only be on training data 
    training_data_validation(train_df)

    # Visualize correlation and perform automatic correlation checks on training data
    correlation_validation(train_df, plots_path) 

    # Save cleaned dataframes as .csv
    train_df.to_csv(f"{write_path}_train.csv", index=False)
    test_df.to_csv(f"{write_path}_test.csv", index=False)

    return train_df, test_df

def save_altair_chart(chart, filename, folder, scale_factor=2.0):
    """
    Save an Altair chart to a file.
    
    Parameters:
        chart (alt.Chart): The Altair chart object.
        filename (str): Output filename with file type specified 
        (.png, .jpg, etc), e.g., "figure_0_2.png".
        folder (str): Path to folder where images will be saved.
        scale_factor (float): Resolution scaling for clarity.
    """
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, filename)
    
    chart.save(path, scale_factor=scale_factor)
    print(f"Saved plot → {path}")

def data_cleaning(raw_df, BASELINE_TEMP = 8.59):
    # BASELINE_TEMP = 8.59 set by our data source, BASELINE TEMP is Jan 1951–Dec 1980 land-average temperature in celsius

    # Drop Date Number column
    df = raw_df.drop(columns=['Date Number'])

    # Create Temperature column by converting Anomaly back to raw temperatures
    df['Temperature'] = df['Anomaly'] + BASELINE_TEMP

    # Create Month_Name column from Month Numbers
    month_dict = {
        1: 'January',
        2: 'February',
        3: 'March',
        4: 'April',
        5: 'May',
        6: 'June',
        7: 'July',
        8: 'August',
        9: 'September',
        10: 'October',
        11: 'November',
        12: 'December'
    }
    df['Month_Name'] = df['Month'].map(month_dict)
    
    # Order Month_Name's as categorical
    df['Month_Name'] = pd.Categorical(df['Month_Name'], categories=list(month_dict.values()), ordered=True)

    return df

def all_data_validation(df):
    # ------------------------------------------------------------
    # Expected Column Names in Correct Order
    # Used as a reference to ensure dataset structure is correct.
    # ------------------------------------------------------------
    expected_columns = [
        "Year", "Month", "Day", "Day of Year",
        "Anomaly", "Temperature", "Month_Name"
    ]
    
    # ------------------------------------------------------------
    # Pandera Data Validation Schema for Daily Temperature Dataset
    # This schema verifies:
    # - Columns exist and are correctly typed
    # - Date values are within realistic bounds
    # - Month names match expected categories
    # - No missing values in critical columns
    # - No duplicate rows
    # - No extra or unexpected columns appear
    # ------------------------------------------------------------
    DailyTempSchema = pa.DataFrameSchema(
    
        # --------------------------------------------------------
        # COLUMN DEFINITIONS
        # Each column has:
        # - A required Python/NumPy dtype
        # - Optional value-range checks
        # - `nullable=False` ensures no missing values allowed
        # --------------------------------------------------------
        columns = {
    
            # Year should be a reasonable calendar year.
            "Year": Column(int, Check.in_range(1800, 2100), nullable=False),
    
            # Month must be between 1–12.
            "Month": Column(int, Check.in_range(1, 12), nullable=False),
    
            # Day of month must be between 1–31.
            "Day": Column(int, Check.in_range(1, 31), nullable=False),
    
            # Day of Year must be between 1–366.
            "Day of Year": Column(int, Check.in_range(1, 366), nullable=False),
    
            # Data Collection Limits for Target and Transformed Target based on
            # minimum and maximum value of baseline temp (our data is the average)  
            # Limits this high should never be practically seen in the date range
            # (min baseline temp - avg baseline temp, max baseline temp - avg baseline temp)
            "Anomaly": Column(float, Check.in_range(-5.64, 5.81), nullable=False),
    
            # Temperature = Anomaly + BASELINE, so numeric
            # range obtained from resources cited below, see explanation
            "Temperature": Column(float, Check.in_range(2.95, 14.40), nullable=False),
    
            # Month names must exactly match the expected categorical list.
            "Month_Name": Column(
                str,
                Check.isin([
                    'January','February','March','April','May','June',
                    'July','August','September','October','November','December'
                ]),
                nullable=False
            ),
        },
    
        # --------------------------------------------------------
        # DATAFRAME-WIDE CHECKS
        # Ensures no duplicated rows exist.
        # --------------------------------------------------------
        checks = [
            Check(lambda df: df.drop_duplicates().shape[0] == df.shape[0])
        ],
    
        # --------------------------------------------------------
        # STRICT MODE
        # Ensures **no extra/unexpected columns** are allowed.
        # --------------------------------------------------------
        strict=True,
    
        # --------------------------------------------------------
        # COERCE MODE
        # Automatically converts data types if possible.
        # Eg: "2020" → 2020 if dtype=int is required.
        # --------------------------------------------------------
        coerce=True
    )

    # Run Validation
    try:
        df = DailyTempSchema.validate(df)
        print("✓ All Data Data validation passed")
    except pa.errors.SchemaError as e:
        print("✗ All Data Data validation failed")
        print('\nValidation Test DataFrame Schema Error Thrown:\n')
        print('Error Type: ', type(e))
        print('Error Name: ', type(e).__name__)
        print('Failure Cases:\n', e.failure_cases)
        error_cases = e.failure_cases
        # Convert the error message to a JSON string
        error_message = json.dumps(e.message, indent=2)
        logging.error("\n" + error_message)
        # print(e) # Verbose error print option
        warnings.warn('Schema Error(s) Logged \n Evaluate Failures Before Proceeding')

    return df

def split_data(df, cutoff = 2012):
    # Split into training and test dataframes based on decided cutoff
    test_df = df[df['Year'] > cutoff]
    train_df = df[df['Year'] <= cutoff]
    return train_df, test_df

def visualize_distribution(train_df, plots_path):
    # -----------------------------------------------------------
    # Target Distribution Visualization (Training Data)
    # -----------------------------------------------------------
    # Source/Adaptation: 531 Lecture 6 Notes & Altair User Guide
    # Purpose: Visualize distributions of target variables (Temperature & Anomaly)
    # on the training dataset only. This helps inform validation schema limits.
    # Right-skewness is expected due to increasing anomalies in recent years.
    
    # ------------------------
    # Temperature Histogram
    # ------------------------
    temp_hist = alt.Chart(train_df).mark_bar().encode(
        x=alt.X('Temperature:Q', bin=alt.Bin(maxbins=50), title='Temperature [°C]'),  # Bin numerical values
        y=alt.Y('count()')  # Count of observations per bin
    ).properties(
        width=500,  # width for side-by-side layout
        height=300,
        title='Temperature Distribution'
    )
    
    # Add mean line (red) to indicate average Temperature
    temp_mean = alt.Chart(train_df).mark_rule(color="red").encode(
        x="mean(Temperature):Q",
        size=alt.value(2)
    )
    
    # Add median line (black) to indicate central tendency
    temp_med = alt.Chart(train_df).mark_rule(color="black").encode(
        x="median(Temperature):Q",
        size=alt.value(2)
    )
    
    # Combine histogram with mean and median lines
    temp_hist = temp_hist + temp_mean + temp_med

    # ------------------------
    # Anomaly Histogram
    # ------------------------
    anomaly_hist = alt.Chart(train_df).mark_bar(color='orange').encode(
        x=alt.X('Anomaly:Q', bin=alt.Bin(maxbins=50), title='Anomaly [°C]'),  # Bin numerical values
        y=alt.Y('count()')
    ).properties(
        width=500,
        height=300,
        title='Anomaly Distribution'
    )
    
    # Add mean line for Anomaly
    anom_mean = alt.Chart(train_df).mark_rule(color="red").encode(
        x="mean(Anomaly):Q",
        size=alt.value(2)
    )
    
    # Add median line for Anomaly
    anom_med = alt.Chart(train_df).mark_rule(color="black").encode(
        x="median(Anomaly):Q",
        size=alt.value(2)
    )
    
    # Combine histogram with mean and median lines
    anomaly_hist = anomaly_hist + anom_mean + anom_med
    
    # ------------------------
    # labels for mean and median on each plot
    # ------------------------
    temp_labels = (
        alt.Chart(train_df).mark_text(dx=-40, dy=-5, color='black').encode(
            x='median(Temperature):Q',
            y=alt.value(10),  # Fixed height for text
            text=alt.value('Median')
        ) +
        alt.Chart(train_df).mark_text(dx=40, dy=-5, color='red').encode(
            x='mean(Temperature):Q',
            y=alt.value(10),
            text=alt.value('Mean')
        )
    )
    
    anomaly_labels = (
        alt.Chart(train_df).mark_text(dx=-40, dy=-5, color='black').encode(
            x='median(Anomaly):Q',
            y=alt.value(10),
            text=alt.value('Median')
        ) +
        alt.Chart(train_df).mark_text(dx=40, dy=-5, color='red').encode(
            x='mean(Anomaly):Q',
            y=alt.value(10),
            text=alt.value('Mean')
        )
    )
    
    # ------------------------
    # Display histograms side by side
    # ------------------------
    
    plot = (temp_hist + temp_labels) | (anomaly_hist + anomaly_labels)

    # ------------------------
    # Save figure
    # ------------------------

    save_altair_chart(plot, "temperature_and_anomaly_distributions.png", plots_path)


def training_data_validation(train_df):
    # -----------------------------------------------------------
    # Training Data Validation Schema
    # -----------------------------------------------------------
    # We intentionally validate *only the training set* against
    # target-distribution assumptions. This avoids leaking
    # information from the held-out test set and respects the
    # golden rule of model validation.
    #
    # Note: Pandera schemas aren’t easily "extended", so we
    # re-initialize a fresh schema specifically for the training
    # portion of the dataset.
    
    target_train_schema = pa.DataFrameSchema(
    
        columns={
            # Core temporal structure checks
            # Bounds are based on historical global temperature
            # ranges and documented dataset limits (see report).
            "Year": Column(int, Check.in_range(1800, 2100), nullable=False),
            "Month": Column(int, Check.in_range(1, 12), nullable=False),
            "Day": Column(int, Check.in_range(1, 31), nullable=False),
            "Day of Year": Column(int, Check.in_range(1, 366), nullable=False),
    
            # Climate measurements with externally justified limits
            "Anomaly": Column(
                float,
                Check.in_range(-5.64, 5.81),   # validated from Berkeley Earth summaries
                nullable=False
            ),
            "Temperature": Column(
                float,
                Check.in_range(2.95, 14.40),   # validated from TMIN/TMAX summaries
                nullable=False
            ),
    
            # Human-readable month names used for categorical checks
            "Month_Name": Column(
                str,
                Check.isin([
                    'January','February','March','April','May','June',
                    'July','August','September','October','November','December'
                ]),
                nullable=False
            )
        },
    
        checks=[
            # Ensure no duplicate rows are present in training data
            Check(lambda df: df.drop_duplicates().shape[0] == df.shape[0]),
    
            # Ensure no fully-empty rows slipped into the dataset
            Check(lambda df: ~(df.isna().all(axis=1)).any(),
                  error="Empty rows found."),
    
            # -------------------------------------------------------
            # Distribution Checks for the TRAINING TARGET
            # -------------------------------------------------------
            # These checks enforce that the distribution of the
            # target (Temperature / Anomaly) behaves as expected
            # based on historical climate patterns.
            #
            # Important: These checks MUST NOT be applied to
            # the test set, as that would leak distributional
            # information and bias evaluation.
    
            # Temperature expected to be slightly right-skewed
            Check(lambda df: df["Temperature"].mean() > df["Temperature"].median(),
                  error="Temperature Distribution Left-skewed"),
    
            # Anomaly expected to be slightly right-skewed
            Check(lambda df: df["Anomaly"].mean() > df["Anomaly"].median(),
                  error="Anomaly Distribution Left-skewed"),
        ],
    
        strict=True,     # Reject datasets with unexpected extra columns
        # coerce=True      # Attempt safe type coercion when appropriate
    )
    
    # -----------------------------------------------------------
    # Validation Execution Block
    # -----------------------------------------------------------
    try:
        # Attempt to validate the training dataset
        train_df = target_train_schema.validate(train_df)
        print("✓ Training Data Data validation passed")
    
    except pa.errors.SchemaError as e:
        # Provide structured diagnostics to help debug failures
        print("✗ Training Data Data validation failed")
        print("\nValidation Test DataFrame Schema Error Thrown:\n")
        print("Error Type: ", type(e))
        print("Error Name: ", type(e).__name__)
        print("Failure Cases:\n", e.failure_cases)
    
        # Store failure details in logs for later inspection
        error_message = json.dumps(e.failure_cases, indent=2)
        logging.error("\n" + error_message)
    
        # Show a runtime warning to halt downstream steps
        warnings.warn("\n Schema Error(s) Logged \n Evaluate Failures Before Proceeding")

    return train_df

def correlation_validation(train_df, plots_path):
    # -----------------------------------------------------------
    # Correlation Analysis for Training Data
    # -----------------------------------------------------------
    # Adapted from:
    # https://github.com/skysheng7/DSCI522_data_validation_demo/tree/main/notebooks
    #
    # This block computes pairwise correlations only on the TRAINING
    # dataset. We exclude the test set to avoid learning anything about
    # relationships in data the model should not "see" during training.
    
    # Drop the Month_Name column since it is categorical and not suitable
    # for Pearson correlation computation
    correlation_matrix = train_df.drop(columns=['Month_Name']).corr()
    
    # Convert the wide correlation matrix into a tidy long format
    # so it can be easily plotted with Altair
    correlation_long = correlation_matrix.reset_index().melt(id_vars='index')
    
    # Rename columns for clarity in the visualization
    correlation_long.columns = ['Feature 1', 'Feature 2', 'Correlation']
    
    # -----------------------------------------------------------
    # Correlation Heatmap Visualization
    # -----------------------------------------------------------
    # We use Altair's rect marks to create a clean, color-coded
    # heatmap showing linear correlations between features.
    # The viridis colormap provides perceptually uniform shading.
    
    heatmap = alt.Chart(correlation_long).mark_rect().encode(
        x='Feature 1:O',   # Treat feature names as ordered categorical axes
        y='Feature 2:O',
        color=alt.Color('Correlation:Q', scale=alt.Scale(scheme='viridis')),
        tooltip=['Feature 1', 'Feature 2', 'Correlation']  # Hover info for inspection
    )
    
    # Add correlation values directly on top of the heatmap tiles
    text = alt.Chart(correlation_long).mark_text(
        baseline='middle',
        fontSize=10,
        fontWeight='bold'
    ).encode(
        x='Feature 1:O',
        y='Feature 2:O',
        text=alt.Text('Correlation:Q', format=".2f"),
        color=alt.condition(
            "abs(datum.Correlation) > 0.5",   # Choose label color based on contrast
            alt.value("white"),
            alt.value("black")
        )
    )
    
    # Combine and render both layers
    heatmap_plot = (heatmap + text).properties(
        **plot_size,        # Uses preset size settings for consistency
        title="Correlation Heatmap"
    )

    # Save plot image
    save_altair_chart(heatmap_plot, "correlation_heatmap.png", plots_path)
    
    #Correlation validations
    # Adapted from https://github.com/skysheng7/DSCI522_data_validation_demo/tree/main/notebooks
    
    temp_train_ds = Dataset(train_df.drop(columns=['Temperature','Year']), label="Anomaly", cat_features=['Month_Name'])
    
    check_feat_lab_corr = FeatureLabelCorrelation().add_condition_feature_pps_less_than(0.9)
    check_feat_lab_corr_result = check_feat_lab_corr.run(dataset=temp_train_ds) # Any correlation near 1 should be examined
    
    temp_train_ds = Dataset(train_df.drop(columns=['Month','Temperature','Year', 'Month_Name']), label="Anomaly", cat_features=[])
    
    check_feat_feat_corr = FeatureFeatureCorrelation().add_condition_max_number_of_pairs_above_threshold(threshold = 0.9, n_pairs = 0)
    check_feat_feat_corr_result = check_feat_feat_corr.run(dataset=temp_train_ds) # Any correlation near 1 should be examined
    
    if not check_feat_lab_corr_result.passed_conditions():
        warnings.warn("\nFeature-Label correlation exceeds the maximum acceptable threshold.")
    
    if not check_feat_feat_corr_result.passed_conditions():
        warnings.warn("\nFeature-feature correlation exceeds the maximum acceptable threshold.")
    
    
    # Setup Altair renderer in Docker and lift the max limit for the rows
    alt.renderers.enable('mimetype') # alternative: alt.renderers.enable('html')
    alt.data_transformers.enable('default', max_rows=None)
    
    # -----------------------------------------------------------
    # Visualize why Day of Year and Month are correlated
    # -----------------------------------------------------------
    
    # Base scatterplot
    scatter = alt.Chart(train_df).mark_point(opacity=0.3, color='blue').encode(
        x='Day of Year:Q',
        y='Month:Q'
    )
    
    # Smoothed trend line to show the linear relationship
    trend = alt.Chart(train_df).mark_line(color='orange', size=3).transform_loess(
        'Day of Year', 'Month', bandwidth=0.3
    ).encode(
        x='Day of Year:Q',
        y='Month:Q'
    )
    
    # Layer both charts
    scatter_plot = (scatter + trend).properties(
        **plot_size,
        title='Month vs Day of Year Correlation'
    )

    # Save plot image
    save_altair_chart(scatter_plot, "month_vs_day_of_year_correlation.png", plots_path)

if __name__ == "__main__":
    main()